### PR TITLE
Release/0.6.0

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

Release Navigator module and Login page plus security fixes

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-dashboard/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-dashboard/blob/main/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac-dashboard/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-dashboard/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by cbkerr** [comment]
The run of the `Publish to TestPyPI` check after the pre-commit bot failed, but I think the publication worked because the URL is live: https://test.pypi.org/project/signac-dashboard/0.6.0/

**Review by tommy-waltmann — APPROVED** [review]
It looks like it uploaded right, but it may still be worth looking the failure report. Is that action failing something that typically happens on release?

**Comment by cbkerr** [comment]
> It looks like it uploaded right, but it may still be worth looking the failure report. Is that action failing something that typically happens on release?

I should have pasted the error, but yes it was that the file was uploaded already:

```
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         File already exists. See https://test.pypi.org/help/#file-name-reuse   
         for more information. 
```

**Comment by joaander** [comment]
> > It looks like it uploaded right, but it may still be worth looking the failure report. Is that action failing something that typically happens on release?
> 
> I should have pasted the error, but yes it was that the file was uploaded already:
> 
> ```
> WARNING  Error during upload. Retry with the --verbose option for more details. 
> ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
>          File already exists. See https://test.pypi.org/help/#file-name-reuse   
>          for more information. 
> ```
> 
> I recall something like this happening on an earlier release where there were extra steps (and one time where I made the version tag wrong) but I think any Slack chat history about it is deleted bc it's been more than 90 days.

I use the `skip_existing` option to silence this type of error:
https://github.com/glotzerlab/gsd/blob/de226fed1862ae2a3a76ac9ef06ce6df4eb970f5/.github/workflows/build_wheels.yml#L99C2-L107

The alternative is to add a suffix to the generated wheel so that each upload succeeds. However, you may then accumulate MANY wheels in the testpypi project.

**Comment by bdice** [comment]
Historically this has always failed if multiple commits are pushed to a release branch — and “skip existing” sounds like the right way to fix this problem. I wasn’t aware of that option when I set up the deployment workflow but would support adding that flag.

**Pull request merged**
