### PR TITLE
New logo / favicon

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR updates the logo. This has a sample favicon, which will also be used for the website.

## Motivation and Context
New logo = new look.

## Types of Changes

- [x] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-dashboard/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-dashboard/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-dashboard/blob/master/contributors.txt).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-dashboard/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-dashboard/blob/master/changelog.txt).

### CODE REVIEW

**Comment by bdice** [comment]
# Screenshots
image
image

**Comment by bdice** [comment]
To clarify, the final version of this will be stacked with a wordmark like the sample image I previously sent, also pasted below. We're doing some final revisions on the wordmark font, so I didn't include that yet. The favicon is ready for review and the style of the sidebar is open for discussion.

**Question for reviewers:** Do you prefer the sidebar with two shades of dark gray (as below) or one shade split by a colorful bar (as above)?

image

**Comment by csadorf** [comment]
> * Do you prefer the sidebar with two shades of dark gray (as below) or one shade split by a colorful bar (as above)? I liked the darker shade behind the logo, since it has greater contrast.

I prefer the two shades of gray.

> * I tried to do some sharpening on the favicon. If you think it needs more work, please let me know. The current image is 96x96 and is being downsized to 16x16. I chose to include a higher-resolution default because it will look best on high-DPI screens (e.g. modern Macs, all phones and tablets, some Windows PCs, 4k TVs). If we choose to use a smaller image that we hand-tune to be sharper, then it may look slightly worse on high-resolution displays.

I think it's too blurry, my screen resolution is 1080p.

**Comment by mikemhenry** [comment]
I like the two greys!

**Comment by mikemhenry** [comment]
At least on my screen it looks good 
image

**Comment by bdice** [comment]
@glotzerlab/signac-maintainers 
The logo doesn't stand off against the lighter gray very well, but I can go with that if @csadorf and @mikemhenry agree on it. Here's the previous two-grays concept again, except as an actual webpage screenshot instead of in Photoshop.
image
FYI, this is what someone would see with monochromacy / achromatopsia / if this were printed in black and white. Notice how many of the stripes are not visible.
image
Here is an alternate take with the grays reversed (for higher contrast behind the logo) and an orange border. Let me know if you like this instead.
image
This is that higher-contrast version in monochrome:
image
I'm still planning to use the "stacked" logo with the text instead of the palette alone -- just trying to pick a docs design while that is finalized.

**Comment by mikemhenry** [comment]
I like the darker gray, excited to see how it looks with the stacked logo!

**Comment by bdice** [comment]
I really like how this is turning out.
image

**Comment by bdice** [comment]
@mikemhenry I’ll merge this after you approve. I would like a unanimous vote among maintainers before adapting the other packages.

**Pull request merged**
