### PR TITLE
Update APIs / internals for signac 2.

### PR DESCRIPTION
**Pull request by bdice**
## Description
This is a continuation of the migrations to signac 2.0 started in #153 (which tackled migrations suitable for signac 1.8.0). This PR should not be merged until signac 2.0 is considered API stable / near release.

## Checklist:
- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-dashboard/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-dashboard/blob/master/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [x] The [package documentation](https://github.com/glotzerlab/signac-dashboard/tree/master/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-dashboard/blob/master/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by b-butler** [comment]
This seems to work for me on my project.

**Review by b-butler — APPROVED** [review]

**Comment by Charlottez112** [comment]
> signac 2.0 (install a development copy from the `master` branch of the signac repository)

How does one do this?

**Comment by bdice** [comment]
@Charlottez112 Clone the repo and install from source with `pip install -e .`.

We need to update this guide (https://docs.signac.io/en/latest/installation.html#installation-from-source) with that command since we moved away from a setup.py build.

**Comment by bdice** [comment]
> > @Charlottez112 Clone the repo and install from source with `pip install -e .`.
> 
> I tried this and it installed `1.8.0`. Is this expected?

Did you use the `master` branch of the signac repo? If so, you’re getting the right package. That will report version 1.8.0 because 2.0.0 has not yet been released. The version tag is updated when releases are made.

**Comment by Charlottez112** [comment]
Worked for me.

**Review by Charlottez112 — APPROVED** [review]

**Pull request merged**
