### PR TITLE
Add DocumentEditor feature

### PR DESCRIPTION
**Pull request by bdice**
Created a feature similar to Notes that allows users to edit the job document directly in the dashboard.

To Do:
 - [x] Clean up error message HTML (so it wraps)
 - [x] Mark saving errors in red!

### CODE REVIEW

**Comment by bdice** [comment]
@glotzerlab/signac-developers I'd appreciate some thoughts on the user interface for this Job Document Editor module. It uses `ast.literal_eval` to ensure that lists and dicts are preserved in the document.
image

**Comment by csadorf** [comment]
Aren't there existing DOM elements for the modification of tree-like structures? As a user I would expect something more along these lines: http://www.htmldrive.net/items/show/203/CSS-and-Javascript-Style-your-Sitemaps-tree-menu

**Comment by bdice** [comment]
@csadorf Thanks for the feedback! It would be possible (but rather difficult) to do something like what you linked. There aren't really DOM elements made for this. It takes a considerable amount of customizing nested `<ul>` structures with JS/CSS since you have to deal with dynamic hiding/showing, and that's before we even add form fields. Hierarchical dynamic forms are super messy to write, from my experience. In general I prefer to stick to elements included in Bulma, for simplicity: https://bulma.io/documentation/

**Comment by csadorf** [comment]
@bdice Got it. I think that the elements you are presenting are much better than nothing and I'm all for moving forward with that, I just think that they will be hard to work with when it comes to non-trivial hierarchical documents.

**Pull request merged**
