### PR TITLE
Link to the discussion board.

### PR DESCRIPTION
**Pull request by joaander**
## Description

Replace the `signac-support` email address and slack link with a link to the signac discussion board.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-dashboard/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-dashboard/blob/main/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac-dashboard/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-dashboard/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Comment by joaander** [comment]
Review the updated page here: https://signac--225.org.readthedocs.build/projects/dashboard/en/225/support.html

**Review by cbkerr — APPROVED** [review]
Thanks!

**Comment by bdice** [comment]
@joaander @cbkerr Hi, is there a policy change around Slack? Are you hoping to retire the Slack workspace?

**Comment by joaander** [comment]
> @joaander @cbkerr Hi, is there a policy change around Slack? Are you hoping to retire the Slack workspace?

No, there is no policy change. I do not have permissions to control the Slack workspace.

**Pull request merged**
