### PR TITLE
Increase search-box size.

### PR DESCRIPTION
**Pull request by csadorf**
Increase search box size to 100.

### CODE REVIEW

**Comment by bdice** [comment]
This PR sets a fixed size for the search bar. This can be problematic on certain screen sizes, like this.
image
See how it overflows on the right?

The best solution is to use responsive design that doesn't depend on screen size. I am going to update this PR so that it scales the search bar to the maximum available width.

**Comment by bdice** [comment]
I spent some time trying to figure out what combination of CSS properties would make this responsive - no luck yet. It's tricky since we want a responsive form input _inside_ of the navbar. After some more testing, I might file an issue with bulma if nothing works. https://github.com/jgthms/bulma/issues.

A temporary fix would be to decrease the size of the search box a bit so that it will never extend beyond the available screen area at a width of 1024px -- this is the break point, below which a different layout is used. From brief testing, I think that `size=60` would satisfy that.

**Comment by csadorf** [comment]
Can we maybe merge the work-around and add responsiveness in a subsequent PR?

**Comment by bdice** [comment]
@csadorf I applied this change to size=60 and also fixed an annoying bug where search queries disappeared from the search box if they were invalid (making it difficult to correct mistakes in the search query).

**Pull request merged**
