### PR TITLE
Support werkzeug and flask updates

### PR DESCRIPTION
**Pull request by cbkerr**
## Description

1. Replaces `werkzeug.urls.url_encode` with `urllib.parse.urlencode` [as recommended](https://github.com/pallets/werkzeug/pull/2768/files#diff-342c3ac7878fc8165fb66b641c3a05ae0b4e5da5c9273fd00db272d61422bb89L1226).

2. Bumps flask_assets minimum version. Unfortunately, `flask_assets `[hasn't been released on conda-forge yet](https://github.com/conda-forge/flask-assets-feedstock/pull/5), but 2.1.0 works when i get it from pypi.
v2.0.0 still uses code removed from flask.
```
    from flask_assets import Bundle, Environment
../../.local/lib/python3.9/site-packages/Flask_Assets-2.0-py3.9.egg/flask_assets.py:8: in <module>
    from flask import _request_ctx_stack, current_app
E   ImportError: cannot import name '_request_ctx_stack' from 'flask' (/Users/Corwin/miniconda3/envs/signac-dev/lib/python3.9/site-packages/flask/__init__.py)
```
3. Bumps flask-login version to[ >0.6.3](https://github.com/maxcountryman/flask-login/blob/0.6.3/CHANGES.md#version-063)

The tests pass and I also ran dashboard locally.

I didn't test with outdated flask or werkzeug however.

### Deprecation in login settings: cannot disable login.
NOTE: I was not able to set `{"ACCESS_TOKEN": None, "SECRET_KEY": None}` in the config settings. I got this error:
```
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
```

## Motivation and Context

Try to resolve tangle of dependency issues created from werkzeug, flask, flask-login, flask-assets updating at different times.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac-dashboard/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac-dashboard/blob/main/ContributorAgreement.md).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac-dashboard/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac-dashboard/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

### CODE REVIEW

**Review by joaander — APPROVED** [review]
Missing packages on conda-forge block a release on conda-forge from supporting flask 3.0, but doesn't block this pull request or a pypi release.

Are you sure that setting `SECRET_KEY=None` worked before? You need a valid secret key to encrypt the session cookies. Setting `ACCESS_TOKEN=None` and not setting `SECRET_KEY` should be sufficient to disable the login requirement:
https://github.com/glotzerlab/signac-dashboard/blob/5ece7d6d8ccb685fc35144000dce28eaaef8baf7/signac_dashboard/dashboard.py#L138-L140

You can restore support for flask 2.0 with:
```
flask >=2.1.0
flask-assets >=2.0.0
flask-login >=0.6.0
```
This is tested (and passes) on CI:
https://github.com/glotzerlab/signac-dashboard/blob/5ece7d6d8ccb685fc35144000dce28eaaef8baf7/.github/workflows/run-pytest.yml#L29

**Comment by cbkerr** [comment]
I also tested locally to make sure this also works:

```
flask=2.1.0
werkzeug=2.1.0

flask-assets=2.1.0
flask-login=0.6.3
```

**Comment by cbkerr** [comment]
> Are you sure that setting SECRET_KEY=None worked before?

Maybe I was mistaken back then or misled by browser caching. Anyway, now `"ACCESS_TOKEN": None` disables the login page.

**Comment by joaander** [comment]
> > Are you sure that setting SECRET_KEY=None worked before?
> 
> Maybe I was mistaken back then or misled by browser caching. Anyway, now `"ACCESS_TOKEN": None` disables the login page.

I couldn't find the source of that message with a github code search. It is possible that some change in flask 3 or a transitive dependency previously allowed `SECRET_KEY=None` and no longer does.

**Review by tommy-waltmann — APPROVED** [review]

**Pull request merged**
